name: dart_z3
description: Holds Dart-like bindings for the C api of Z3 Theorem Prover, version (4.8.17).
version: 1.0.3
repository: https://github.com/IvoSchols/dart-z3

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0