// enum Z3_sort_kind {
//   Z3_UNINTERPRETED_SORT,
//   Z3_BOOL_SORT,
//   Z3_INT_SORT,
//   Z3_REAL_SORT,
//   Z3_BV_SORT,
//   Z3_ARRAY_SORT,
//   Z3_DATATYPE_SORT,
//   Z3_RELATION_SORT,
//   Z3_FINITE_DOMAIN_SORT,
//   Z3_FLOATING_POINT_SORT,
//   Z3_ROUNDING_MODE_SORT,
//   Z3_SEQ_SORT,
//   Z3_RE_SORT,
//   Z3_CHAR_SORT,
//   Z3_UNKNOWN_SORT,
// }

enum Z3_ast_kind {
  Z3_NUMERAL_AST,
  Z3_APP_AST,
  Z3_VAR_AST,
  Z3_QUANTIFIER_AST,
  Z3_SORT_AST,
  Z3_FUNC_DECL_AST,
  Z3_UNKNOWN_AST
}
